version: '3.8'

services:
  lamp:
    image: webdevops/php-apache:8.2
    # platform: linux/arm64
    restart: unless-stopped
    container_name: lamp
    volumes:
      - ~/public_html:/app
    ports:
      - "80:80"
    environment:
      WEB_DOCUMENT_ROOT: /app
    depends_on:
      - db

  db:
    image: mysql:8.0-oracle
    platform: linux/arm64
    restart: unless-stopped
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: test
      MYSQL_USER: sergey
      MYSQL_PASSWORD: 12345678
    volumes:
      - ~/docker_data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
